# vim: tabstop=4 shiftwidth=4 softtabstop=4
#
# Copyright 2013 OpenStack LLC
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""empty message

Revision ID: 145a1a43e291
Revises: 2a4ae01081a6
Create Date: 2013-02-10 11:07:26.820911

"""


# revision identifiers, used by Alembic.
revision = '145a1a43e291'
down_revision = '2a4ae01081a6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(options=None):
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('letter', sa.Unicode(length=10), nullable=False))
    op.drop_column('currency', u'code')
    op.add_column('language', sa.Column('letter', sa.Unicode(length=10), nullable=False))
    op.drop_column('language', u'code')
    ### end Alembic commands ###


def downgrade(config=None):
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('language', sa.Column(u'code', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('language', 'letter')
    op.add_column('currency', sa.Column(u'code', mysql.VARCHAR(length=10), nullable=False))
    op.drop_column('currency', 'letter')
    ### end Alembic commands ###
