# vim: tabstop=4 shiftwidth=4 softtabstop=4
#
# Copyright 2013 OpenStack LLC
#
#    Licensed under the Apache License, Version 2.0 (the "License"); you may
#    not use this file except in compliance with the License. You may obtain
#    a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#    WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#    License for the specific language governing permissions and limitations
#    under the License.
#

"""empty message

Revision ID: 2a4ae01081a6
Revises: f047fb12bf
Create Date: 2013-02-10 10:47:07.484311

"""


# revision identifiers, used by Alembic.
revision = '2a4ae01081a6'
down_revision = 'f047fb12bf'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade(options=None):
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency', u'code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('currency', u'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('language', u'code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    op.alter_column('language', u'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    ### end Alembic commands ###


def downgrade(config=None):
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('language', u'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('language', u'code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column('currency', u'name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('currency', u'code',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    ### end Alembic commands ###
